version: '3.8'

services:
  # Serviço PHP com Symfony (similar ao Spring Boot)
  php:
    image: php:8.2-cli
    container_name: symfony_app
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DATABASE_URL=mysql://symfony_user:symfony_pass@mysql:3306/symfony_db
    depends_on:
      - mysql
    networks:
      - symfony_network
    command: >
      bash -c "
        # Instalar dependências do sistema
        apt-get update &&
        apt-get install -y git unzip curl libzip-dev libpng-dev libonig-dev libxml2-dev &&
        
        # Instalar extensões PHP necessárias
        docker-php-ext-install pdo pdo_mysql mbstring zip exif pcntl bcmath gd &&
        
        # Instalar Composer
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        
        # Instalar Symfony CLI
        curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash &&
        apt-get install -y symfony-cli &&
        
        # Manter o container rodando (como um Spring Boot app)
        tail -f /dev/null
      "

  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - symfony_network

  # PHPMyAdmin para gerenciar o banco
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: symfony_user
      PMA_PASSWORD: symfony_pass
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - symfony_network

  frontend:
    image: node:20-bullseye
    container_name: vue_app
    working_dir: /app
    volumes:
      - ./vue-project/app:/app
    ports:
      - "5173:5173"
    tty: true
    command: tail -f /dev/null
    networks:
      - symfony_network

volumes:
  mysql_data:

networks:
  symfony_network:
    driver: bridge
