nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']  # origem exata do frontend
        allow_credentials: true                  # cookies podem ser enviados
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/': ~
