parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'

    App\Exceptions\ExceptionListener:
            arguments:
                $environment: '%kernel.environment%'
            tags:
                - { name: kernel.event_listener, event: kernel.exception }