version: "3.8"

services:
  frontend:
    image: node:20-bullseye
    container_name: vue_app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    tty: true
    command: tail -f /dev/null
